name: 'Setup Synapse'
description: 'Deploys a synapse test server'
inputs:
  uploadLogs:
    description: 'Upload synapse logs at end'
    required: true
    default: true
  artifactName:
    description: 'Override artifact name for logs'
    required: false
    default: 'synapse-logs'
  customConfig:
    description: 'JSON-formatted custom config for synapse'
    required: false
    default: '{}'
  serverName:
    description: 'The name of the homeserver (or "localhost")'
    required: false
  customModules:
    description: 'Comma-separated list of modules to pip install.'
    required: false
    default: ''
  public_baseurl:
    description: 'Public base URL (defaults to http://localhost:${httpPort} if not defined)'
    required: false
  httpPort:
    description: 'HTTP port for C-S and S-S APIs'
    required: false
    default: 8080
  disableRateLimiting:
    description: 'Disable ratelimiting of server requests'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'dist/create/index.js'
  post: 'dist/destroy/index.js'
  post-if: 'always()'
